site_name: docs::Termage

theme:
  name: material

  custom_dir: docs/overrides

  font:
    text: Open Sans

  features:
  - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-green
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

plugins:
  - search
  - termage

repo_url: https://github.com/bczsalba/termage
repo_name: bczsalba/termage

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Options: options.md
  - In the command line: cli.md
  - As an MkDocs plugin: plugin.md
